set(Plugin-Name "M2aia Registration View")
set(Plugin-Version "0.1")
set(Plugin-Vendor "Mannheim University of Applied Sciences")
set(Plugin-ContactAddress "j.cordes@hs-mannheim.de")
set(Require-Plugin org.mitk.gui.qt.common)
