set(MITK_PLUGINS
org.mitk.m2.core.helper:ON
org.mitk.gui.qt.m2.navigator3d:ON
org.mitk.gui.qt.m2.application:ON
org.mitk.gui.qt.m2.Position:ON
org.mitk.gui.qt.m2.PeakPicking:ON
org.mitk.gui.qt.m2.OpticalImageRegistration:ON
org.mitk.gui.qt.m2.ImzMLExport:ON
org.mitk.gui.qt.m2.Data:ON
org.mitk.gui.qt.m2.Ions:ON
org.mitk.gui.qt.m2.Spectrum:ON
org.mitk.gui.qt.m2.Reconstruction3D:ON
org.mitk.gui.qt.m2.CombineImages:ON
org.mitk.gui.qt.m2.Manipulator:ON
)
