set(MODULE_TESTS
  m2FSMImageIOTest.cpp
  m2ImzMLImageIOTest.cpp
  m2CoreMappingsTest.cpp
  m2ElxUtilTest.cpp
  m2SignalGroupBinningTest.cpp
  m2BaselineTest.cpp
  m2ProcessMapTest.cpp
  m2ToleranceTest.cpp
)
