SET(Plugin-Name "M2aia Core Helper")
set(Plugin-Version "0.1")
set(Plugin-Vendor "Mannheim University of Applied Sciences")
set(Plugin-ContactAddress "j.cordes@hs-mannheim.de")
set(Require-Plugin org.mitk.gui.common)
set(Plugin-ActivationPolicy eager)
