set(Plugin-Name "M²aia Reconstruction 3D")
set(Plugin-Version "0.1")
set(Plugin-Vendor "M2")
set(Plugin-ContactAddress "https://m2aia.de")
set(Require-Plugin org.mitk.gui.qt.common org.mitk.gui.qt.m2.common org.mitk.gui.qt.elastix.registration org.mitk.gui.qt.elastix.common)
