set(Plugin-Name "Geometry Manipulator")
set(Plugin-Version "0.1")
set(Plugin-Vendor "Mannheim University of Applied Sciences")
set(Plugin-ContactAddress "j.cordes@hs-mannheim.de")
set(Require-Plugin org.mitk.gui.qt.common org.mitk.gui.qt.datamanager org.mitk.gui.qt.m2.common)
