SET(Plugin-Name "M2aia Core Helper")
set(Plugin-Version "0.1")
set(Plugin-Vendor "HS Mannheim")
set(Plugin-ContactAddress "j.cordes@hs-mannheim.de")
set(Require-Plugin org.mitk.gui.common)
set(Plugin-ActivationPolicy eager)
