set(Plugin-Name "M2aia Peak Picking")
set(Plugin-Version "0.1")
set(Plugin-Vendor "HS Mannheim")
set(Plugin-ContactAddress "j.cordes@hs-mannheim.de")
set(Require-Plugin org.mitk.gui.qt.common org.mitk.m2.core.helper)
